### ISSUE TITLE
京东美丽研究院运行不了

### ISSUE THREAD

**Issue by godwang11** [he1pu/signin#4]
开始任务：""shop_products"
/ql/scripts/he1pu_JDHelp_jd_beauty.js:240
          let count = $.taskState.shop_view.length;
                                  ^

TypeError: Cannot read properties of undefined (reading 'shop_view')
    at WebSocket.client.onmessage (/ql/scripts/he1pu_JDHelp_jd_beauty.js:240:35)
运行显示这个样子
是哪里没设置好么？

**Comment by he1pu** [comment]
不行就禁用吧。
我完全跑不了了，换ip设置UA都不行。

**Comment by TeslaLyon** [comment]
请问在现在这个时间点，美丽研究院的入口在哪里？
